development:
  adapter: postgresql
  encoding: unicode
  database: ligamx_development
  pool: 5
  username: Acuna
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ligamx_test
  pool: 5
  username: Acuna
  password:
  host: localhost